configs:
  cm:
    timeout.reconciliation: 30s
    accounts.devops: apiKey,login

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, devops, role:admin

server:
  service:
    type: ClusterIP

  extraArgs:
    - --insecure

redis:
  enabled: true
    
    #applicationSet:
    #  enabled: true

